### ISSUE TITLE
refactor routes

### ISSUE THREAD

**Issue by ej2brown** [ej2brown/DevCollabs-refactored#1]
issues
when trying to run server 
$ node server.ts
=> 
Node.js - SyntaxError: Unexpected token import in server.ts for import {IRoutes} from './routes/routes.interface'

- changed to require('')

then
2)
$ node server.ts
=> TypeError: Unknown file extension ".ts"  code: 'ERR_UNKNOWN_FILE_EXTENSION'

-changed to .js extension

then
3)
$ node server.js
=>  const RateExpressRoutes = require('./routes/rate'); require is not defined

-installed webpack and Browserify

**Comment by thecameraguy** [comment]
this is likely because we haven't compiled TS into JS.
We need todo `npm run build`
and run node.js on the compiled server.js. I think package.json needs to be updated to do this automatically. Let me have a look.

**Comment by thecameraguy** [comment]
We will need to put the following in package.json:
```
  "main": "dist/index.js",
  "types": "dist/index.d.js",
  "scripts": {
    "test": "karma start",
    "build": "tsc"
  },
```

And let's add the following to tsconfig.json under compilerOptions:
```
"outDir": "./dist/",
"sourceMap": true,
```

**Comment by thecameraguy** [comment]
To compile, run `npm run build` and you can run the compiled app with `node dist/server.js`

**Comment by thecameraguy** [comment]
@ej2brown Have a look at https://github.com/ej2brown/DevCollabs-refactored/pull/3! I've managed fix the build issue - it was because we were trying to build server's typescrpit and client's reactjs ts code all at the same time. You can now build server separately by doing `npm run build-server` and run it by `node dist/server-src/server.js`

**Comment by ej2brown** [comment]
removed .ts from './dbHelpers/dbHelpers.ts' and some other stuff. Finally works now! Yay!

**Comment by thecameraguy** [comment]
@ej2brown Once we complete the implementation of PostgresController, we should instantiate it from server.ts and pass that in to our IRoutes instances. We should also modify constructors for the Routes classes (RateRoutes, etc) to take db: IDatabaseController. And they should now have m_dbHelper member typed to IDatabaseController
